### ISSUE TITLE
index.md examples use unspecified view lib

### ISSUE THREAD

**Issue by kspeakman** [fable-elmish/fable-elmish.github.io#42]
```fsharp
let view model dispatch =
    Html.div [
        Html.input [
            prop.value model.Value
            prop.onChange (fun value ->
                value |> ChangeValue |> dispatch
            )
        ]
        Html.span [
            prop.text $"Hello, %s{model.Value}!"
        ]
    ]
```

The two examples are using Feliz maybe? The sample repos use Fable.React elements (`element attrs contents` syntax). The React page mentions Fable.Elmish.React, which includes Fable.React.

This seems confusing for new users of Elmish. Can we either: note the view library being used in website examples? Or: change the examples to use Fable.React for consistency with samples?

Either way, open statements are nice to include to show the user how to access modules / fns.

What do you think?

**Comment by MangelMaxime** [comment]
I added the open instruction to the examples on the main page.

We don't have the numbers, but in general I think people prefer to use Feliz nowadays compared to Fable.React because it is easier to structure the code. It's a little more flexible.

Of course, old application, still works with Fable.React.

Now that I am writing this message Elmish is actually renderer agnostric you can use it with React, SolidJS, Lit elements, etc. But I guess for the main page that should be ok to give pointers.

**Comment by kspeakman** [comment]
@MangelMaxime Based on recent articles and comments of prominent community members such as yourself, it seems Feliz is currently preferred. Actual usage, not sure.

Fable.React syntax seems a more stable choice, and is my preference. But I'll go along if Elmish docs want to claim Feliz as a preference. Either way, being consistent between docs/samples would avoid a lot of confusion.

**Comment by kspeakman** [comment]
And thanks for adding the opens! I cannot tell you how many times I have read docs and been frustrated by omitted opens. Having to go on safari just to get the example working.

**Comment by MangelMaxime** [comment]
> Based on recent articles and comments of prominent community members such as yourself, it seems Feliz is currently preferred. Actual usage, not sure.

Coming with the number if kind of difficult.

But what we can say is that:

- Fable.React has 636.0K downloads
- Feliz has 321.8K downloads

But since day one Feliz had a dependency on Fable.React so does that mean that half of the downloads of Fable.React comes from Feliz?

Future versions of Feliz are going to not have Fable.React dependency so we will probably be able to see if Feliz is growing faster than Fable.React :)

**Comment by MangelMaxime** [comment]
Yes regarding, the DSL choice it is not really easy to take a decision on it.

When doing the rewrite, I choosed the one which seems to gain traction at the time. And was easier to fit on a small column for aesthetic reason :)

**Comment by kspeakman** [comment]
I don't have any special attachment to Fable.React. My perspective is from using many UI libs since ~y2k. I'm still maintaining WebForms, jQuery, Angular 1.x, etc UIs from years past. Because they require costly rewrites to move forward, and they were never prioritized. Ultimately I noticed that the HTML standard is always there regardless of what UI lib is popular. So now I align UI to that. Fable.React is our current means to that end. Careful use of it makes F#-based UI that is translatable almost 1:1 to/from HTML. Part of being careful is avoiding proprietary features (e.g. hooks). Preferring F#-based approaches instead. This has trade-offs, but the UI remains evolvable past the sunsetting of specific UI tech/trends. My preference for Fable.React over Feliz is just that F.R DSL -- which compares negatively in some aspects -- aligns more closely with the HTML representation.
